In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.decomposition import PCA
from sklearn.neighbors import LocalOutlierFactor
import sys
from embedding import Graph2Vec
from sqlalchemy import create_engine
import pymysql
import pandas as pd
import os
import datetime
import time

In [2]:
def processingforcorr(data):
        Corr = data.corr().values
        Corr = np.abs(Corr)
        Corr = pd.DataFrame(Corr)
        return Corr.fillna(0).values

def Graph(data):
    maxlag = 1
    test = 'ssr_chi2test'
    X = []
    new = processingforcorr(data.iloc[:24])
    X.append(new)
    i = 1
    while i<=data.shape[0]-25:
        new = processingforcorr(data.iloc[i:i+24])
        X.append(new)
        i=i+24
            
    return np.array(X)

def entropy(X):
        E = []
        for i in range(X.shape[0]):
            P = []
            for j in range(X.shape[1]):
                if i !=j:
                    e =X[i][j]*np.log(X[i][j])
                    P.append(e)
            P = np.array(P)
            E.append(np.sum(P))
        return np.array(E)

def graphentropy(X):
        E = []
        for i in range(X.shape[0]):
            e = entropy(X[i])
            E.append(np.sum(e))
        return np.array(E)

def distance(x,y):
        distance = np.mean(np.power((x,- y),2))
        return distance

def getMatrix(data,E):
        Matrix = []
        for i in range(E.shape[0]):
            dis = []
            for j in range(len(E)):
                dis.append(distance(E[i],E[j]))
            dis = np.array(dis)
            index = np.argsort(dis)[1]
            Matrix.append(data[index])
            
        return np.array(Matrix)

In [6]:
db_connection_str = 'mysql+pymysql://root:caucse1234@caucse.club/virus'
db_connection = create_engine(db_connection_str)
df = pd.read_sql('SELECT test.city,weather.* FROM weather,test where weather.KID=test.KID and weather.date >="2019-01-01" AND weather.date <"2019-01-30"', con=db_connection)

In [7]:
chengshi=["서울특별시","인천광역시","서산","보령","전주","광주광역시","목포","제주특별자치도","여수","부산광역시","울산광역시","대구광역시","구미","안동","영덕","태백","충주","원주","대전광역시","춘천"]

In [8]:
df.loc[df['city']==chengshi[19]]

city  KID                date  qiwen  shidu  zhengqiya  ludianwendu  \
2088   춘천   73 2019-01-01 00:00:00   -9.6   70.0        2.1        -14.0   
2089   춘천   73 2019-01-01 01:00:00  -10.6   74.0        2.0        -14.3   
2090   춘천   73 2019-01-01 02:00:00  -10.7   71.0        1.9        -14.9   
2091   춘천   73 2019-01-01 03:00:00  -11.7   82.0        2.1        -14.1   
2092   춘천   73 2019-01-01 04:00:00  -12.1   80.0        1.9        -14.8   
...   ...  ...                 ...    ...    ...        ...          ...   
2778   춘천   73 2019-01-29 19:00:00    0.2   41.0        2.5        -11.5   
2779   춘천   73 2019-01-29 20:00:00   -2.0   51.0        2.7        -10.8   
2780   춘천   73 2019-01-29 21:00:00   -3.1   56.0        2.7        -10.6   
2781   춘천   73 2019-01-29 22:00:00   -3.5   54.0        2.6        -11.4   
2782   춘천   73 2019-01-29 23:00:00   -4.7   61.0        2.6        -11.0   

      dangdiqiya  haimianqiya  dimianqiya  
2088      1025.9       1036.1        -9.4  
2089      1025.6       1035.8       -10.0  
2090      1025.6       1035.8       -10.3  
2091      1025.9       1036.2       -10.6  
2092      1025.4       1035.7       -10.6  
...          ...          ...         ...  
2778      1017.4       1027.1        -3.6  
2779      1017.5       1027.3        -4.1  
2780      1017.3       1027.2        -4.5  
2781      1017.2       1027.1        -5.1  
2782      1018.0       1027.9        -5.3  

[695 rows x 10 columns]

In [7]:
df1=pd.DataFrame()
df2=pd.DataFrame()
df3=pd.DataFrame()
df4=pd.DataFrame()
df5=pd.DataFrame()
df6=pd.DataFrame()
df7=pd.DataFrame()
df8=pd.DataFrame()
df9=pd.DataFrame()
df10=pd.DataFrame()
df11=pd.DataFrame()
df12=pd.DataFrame()
df13=pd.DataFrame()
df14=pd.DataFrame()
df15=pd.DataFrame()
df16=pd.DataFrame()
df17=pd.DataFrame()
df18=pd.DataFrame()
df19=pd.DataFrame()
df20=pd.DataFrame()
df_list = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20]

In [8]:
s1 = "20200101"
a = time.strptime(s1,'%Y%m%d')
start=a[:3]
s2 = "20200130"
b= time.strptime(s2,'%Y%m%d')
end=b[:3]
starttime=datetime.date(start[0],start[1],start[2])
endtime=datetime.date(end[0],end[1],end[2])
qqq=(endtime-starttime).days
day=[]
for i in range(qqq+1):
    day1=starttime+datetime.timedelta(days=i)
    day.append(str(day1))
dic={}
dic2={}
for key in day:
    dic[key]=0
for key in chengshi:
    dic2[key]=dic

In [9]:
qqq=[1,2,3,4]
for j in range(15):
    for i in range(15):
        dic2[chengshi[j]][day[i]]=qqq

In [10]:
dic2

{'서울특별시': {'2020-01-01': [1, 2, 3, 4],
  '2020-01-02': [1, 2, 3, 4],
  '2020-01-03': [1, 2, 3, 4],
  '2020-01-04': [1, 2, 3, 4],
  '2020-01-05': [1, 2, 3, 4],
  '2020-01-06': [1, 2, 3, 4],
  '2020-01-07': [1, 2, 3, 4],
  '2020-01-08': [1, 2, 3, 4],
  '2020-01-09': [1, 2, 3, 4],
  '2020-01-10': [1, 2, 3, 4],
  '2020-01-11': [1, 2, 3, 4],
  '2020-01-12': [1, 2, 3, 4],
  '2020-01-13': [1, 2, 3, 4],
  '2020-01-14': [1, 2, 3, 4],
  '2020-01-15': [1, 2, 3, 4],
  '2020-01-16': 0,
  '2020-01-17': 0,
  '2020-01-18': 0,
  '2020-01-19': 0,
  '2020-01-20': 0,
  '2020-01-21': 0,
  '2020-01-22': 0,
  '2020-01-23': 0,
  '2020-01-24': 0,
  '2020-01-25': 0,
  '2020-01-26': 0,
  '2020-01-27': 0,
  '2020-01-28': 0,
  '2020-01-29': 0,
  '2020-01-30': 0},
 '인천광역시': {'2020-01-01': [1, 2, 3, 4],
  '2020-01-02': [1, 2, 3, 4],
  '2020-01-03': [1, 2, 3, 4],
  '2020-01-04': [1, 2, 3, 4],
  '2020-01-05': [1, 2, 3, 4],
  '2020-01-06': [1, 2, 3, 4],
  '2020-01-07': [1, 2, 3, 4],
  '2020-01-08': [1, 2, 3, 4],
  '202

In [11]:
for i in range(0,19):
    
    df_list[i]=df.loc[df['city']==chengshi[i]]
df_list[17]        

city  KID                date  qiwen  shidu  zhengqiya  ludianwendu  \
11133   원주   72 2020-01-01 00:00:00   -6.9   50.0        1.8        -15.6   
11134   원주   72 2020-01-01 01:00:00   -6.6   43.0        1.6        -17.1   
11135   원주   72 2020-01-01 02:00:00   -6.1   40.0        1.6        -17.5   
11136   원주   72 2020-01-01 03:00:00   -6.7   55.0        2.0        -14.2   
11137   원주   72 2020-01-01 04:00:00   -6.4   53.0        2.0        -14.4   
...    ...  ...                 ...    ...    ...        ...          ...   
11824   원주   72 2020-01-29 19:00:00    6.9   43.0        4.3         -4.8   
11825   원주   72 2020-01-29 20:00:00    6.4   47.0        4.5         -4.1   
11826   원주   72 2020-01-29 21:00:00    6.4   47.0        4.5         -4.1   
11827   원주   72 2020-01-29 22:00:00    5.7   52.0        4.8         -3.4   
11828   원주   72 2020-01-29 23:00:00    5.5   54.0        4.9         -3.0   

       dangdiqiya  haimianqiya  dimianqiya  
11133      1014.7       1034.3        -4.3  
11134      1014.3       1033.9        -3.3  
11135      1013.8       1033.4        -2.9  
11136      1013.8       1033.4        -3.0  
11137      1013.7       1033.3        -2.8  
...           ...          ...         ...  
11824       996.4       1014.7         1.9  
11825       996.6       1014.9         1.5  
11826       996.7       1015.0         1.8  
11827       996.7       1015.1         1.8  
11828       996.5       1014.9         1.7  

[696 rows x 10 columns]

In [12]:
for i in range(0,19):
    
        df_list[i]=df.loc[df['city']==chengshi[i]]
        df_list[i]=df_list[i].iloc[:,3:]
        x = Graph(df_list[i])
        X = x.reshape(-1,49)
        print(X.shape)

(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)
(29, 49)


In [13]:
a=[]
blist=[]
for i in range(0,19):

        df_list[i]=df.loc[df['city']==chengshi[i]]
        df_list[i]=df_list[i].iloc[:,3:]
        x = Graph(df_list[i])
        X = x.reshape(-1,49)
        
        pca = PCA(n_components=4*4)
        X= pca.fit_transform(X)
        for j in range(X.shape[0]):
            for k in range(X.shape[1]):
                if X[j][k] == 0:
                    X[j][k] = 1
        X = np.abs(X.reshape(X.shape[0],4,4))
        E = graphentropy(X)

        MatrixX = getMatrix(X,E)

        TrainXTensor = torch.from_numpy(X.reshape(X.shape[0], 16)).type(torch.FloatTensor)
        TrainSTensor = torch.from_numpy(MatrixX.reshape(X.shape[0], 16)).type(torch.FloatTensor)
            
        model = torch.load('Model.pth')
        model.eval()
        ed1, ed2, de1, de2 = model(TrainXTensor, TrainSTensor)
        Embed = ed1.data.numpy()

        df_Embed = pd.DataFrame(Embed)
        df_Embed.columns = ['C0','C1','C2','C3','C4','C5','C6','C7','C8','C9']
        blist.append(Embed)
        #for h in range(len(dic2)):
            #for p in range(len(dic)-1):
                #dic2[chengshi[h]][day[p]]=Embed[p]
            
            
     

In [14]:
blist[0][3]

array([ 0.00319158, -0.00192708, -0.00438035, -0.00169067, -0.00202898,
       -0.00058336, -0.00080832,  0.00048456, -0.00180724, -0.00024072],
      dtype=float32)

In [15]:
yyy=np.array(blist)

In [16]:
yyy[0][0]

array([ 0.00278531, -0.00140165, -0.00353891, -0.00157345, -0.00172888,
       -0.000597  , -0.00108539,  0.00045884, -0.0018654 , -0.00040699],
      dtype=float32)

In [17]:
for h in range(0,3):
            for p in range(0,29):
                a=chengshi[h]
                b=day[p]
                if dic2[a][b].all() == 0:
                    dic2[a][b]=blist[h][p]
                else:
                    print('skip')

AttributeError: 'list' object has no attribute 'all'

In [18]:

dic2[chengshi[0]][day[1]]=list(blist[0][1])

In [19]:
dic2

{'서울특별시': {'2020-01-01': [1, 2, 3, 4],
  '2020-01-02': [0.002867321,
   -0.0010626147,
   -0.0038787546,
   -0.0020987222,
   -0.0013676888,
   -0.0006561604,
   -0.0016736746,
   0.0004241507,
   -0.0013755463,
   -0.00063734263],
  '2020-01-03': [1, 2, 3, 4],
  '2020-01-04': [1, 2, 3, 4],
  '2020-01-05': [1, 2, 3, 4],
  '2020-01-06': [1, 2, 3, 4],
  '2020-01-07': [1, 2, 3, 4],
  '2020-01-08': [1, 2, 3, 4],
  '2020-01-09': [1, 2, 3, 4],
  '2020-01-10': [1, 2, 3, 4],
  '2020-01-11': [1, 2, 3, 4],
  '2020-01-12': [1, 2, 3, 4],
  '2020-01-13': [1, 2, 3, 4],
  '2020-01-14': [1, 2, 3, 4],
  '2020-01-15': [1, 2, 3, 4],
  '2020-01-16': 0,
  '2020-01-17': 0,
  '2020-01-18': 0,
  '2020-01-19': 0,
  '2020-01-20': 0,
  '2020-01-21': 0,
  '2020-01-22': 0,
  '2020-01-23': 0,
  '2020-01-24': 0,
  '2020-01-25': 0,
  '2020-01-26': 0,
  '2020-01-27': 0,
  '2020-01-28': 0,
  '2020-01-29': 0,
  '2020-01-30': 0},
 '인천광역시': {'2020-01-01': [1, 2, 3, 4],
  '2020-01-02': [0.002867321,
   -0.0010626147,
   -0

In [136]:
list(blist[0][0])

[0.0027853076,
 -0.0014016533,
 -0.0035389068,
 -0.0015734468,
 -0.0017288817,
 -0.0005970024,
 -0.0010853852,
 0.00045883536,
 -0.0018654015,
 -0.00040698607]

In [88]:
dic2[chengshi[1]][day[29]]

0

In [80]:
blist

[array([ 0.00278531, -0.00140165, -0.00353891, -0.00157345, -0.00172888,
        -0.000597  , -0.00108539,  0.00045884, -0.0018654 , -0.00040699],
       dtype=float32),
 array([ 0.00286732, -0.00106261, -0.00387875, -0.00209872, -0.00136769,
        -0.00065616, -0.00167367,  0.00042415, -0.00137555, -0.00063734],
       dtype=float32),
 array([ 0.00374634, -0.00012433, -0.00409407, -0.00271029, -0.00136713,
        -0.00159035, -0.00303983,  0.0004238 ,  0.0004603 , -0.00110242],
       dtype=float32),
 array([ 0.00319158, -0.00192708, -0.00438035, -0.00169067, -0.00202898,
        -0.00058336, -0.00080832,  0.00048456, -0.00180724, -0.00024072],
       dtype=float32),
 array([ 0.00277896, -0.00227259, -0.00362008, -0.00071646, -0.0031946 ,
        -0.00095704, -0.00045842,  0.00081088, -0.00201099, -0.00024821],
       dtype=float32),
 array([ 0.0019973 , -0.00449158, -0.00281947,  0.00142264, -0.00473662,
        -0.00018613,  0.00263473,  0.00122276, -0.00489951,  0.00076074],
   

In [51]:
seoul=dic2['서울특별시']['2020-01-01']
busan=dic2['부산광역시']['2020-01-01']
guangju=dic2['광주광역시']['2020-01-01']
ulsan=dic2['울산광역시']['2020-01-01']
daqiu=dic2['대구광역시']['2020-01-01']



In [53]:
busan

array([ 0.0032482 , -0.00202404, -0.00442472, -0.00168314, -0.002123  ,
       -0.00087926, -0.00120263,  0.00044099, -0.00167323, -0.00031719],
      dtype=float32)

In [47]:
ppp = np.vstack((a,b,c,d,e))
lof = LocalOutlierFactor(n_neighbors=10, contamination=0.2, algorithm='auto', n_jobs=-1, novelty=True)
lof.fit(ppp)
list(np.abs(lof.negative_outlier_factor_))

f:\Users\caucse\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neighbors\_lof.py:285: UserWarning: n_neighbors (10) is greater than the total number of samples (5). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(


[1.0, 1.0, 1.0, 1.0, 1.0]

In [37]:
lof = LocalOutlierFactor(n_neighbors=10, contamination=0.2, algorithm='auto', n_jobs=-1, novelty=True)
lof.fit(ppp)

f:\Users\caucse\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neighbors\_lof.py:285: UserWarning: n_neighbors (10) is greater than the total number of samples (5). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(


LocalOutlierFactor(contamination=0.2, n_jobs=-1, n_neighbors=10, novelty=True)

In [43]:
y_pred_outliers_LOF = lof.predict(ppp)
list(np.abs(lof.negative_outlier_factor_))

[1.0, 1.0, 1.0, 1.0, 1.0]